repos:
-   repo: git@github.com:doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
    -   id: cargo-check
    -   id: clippy
-   repo: git@github.com:ambv/black
    rev: 23.3.0
    hooks:
    - id: black
      args: [--quiet, --safe]
      language: python
-   repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
